name: Deploy mdBook to GitHub Pages

on:
  push:
    branches:
      - main  # Déploie quand tu pushes sur "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install mdBook
        run: |
          curl -sSL https://github.com/rust-lang/mdBook/releases/latest/download/mdbook-v0.4.37-x86_64-unknown-linux-gnu.tar.gz | head
          sudo mv mdbook /usr/local/bin/mdbook

      - name: Build the book
        run: mdbook build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
